name: Build CI wheels for windows

on:
  # Manual trigger
  workflow_dispatch:
  # Save CI by only running this on release branches or tags.
  push:
    branches:
      - v[0-9]+.[0-9]+.x
    tags:
      - v*

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [windows]
        python-version: ['6', '7', '8', '9']  # , '10' # 3.10 does not work
        cibw_archs: ["auto"]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.8'
      
      # - name: Install numpy
      #   run: pip install numpy==1.22.1  # latest release

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel

      - name: Build wheels for CPython 3.${{ matrix.python-version }}
        run: |
          python -m cibuildwheel --output-dir dist
        env:
          CIBW_BUILD: 'cp3${{ matrix.python-version }}-*'
          CIBW_ARCHS: ${{ matrix.cibw_archs }}
          CIBW_PLATFORM: '${{ matrix.os }}'

      - uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: ./dist/*.whl